import {state,save} from './storage.js';
import {ownedEvents} from './session.js';
const $=id=>document.getElementById(id);let receipts=[],receiptPage=0;
function evidence(){receiptPage=Math.min(receiptPage,Math.max(0,receipts.length-1));const event=receipts[receiptPage];$('seen').textContent=event?JSON.stringify(event.data,null,2)+'\nProject: '+(event.projectId??'Unmatched')+'\nOccurred: '+event.at+'\nEvent: '+event.id:'No permitted site evidence.';$('receiptPage').textContent=event?`${receiptPage+1} / ${receipts.length}`:'None';$('previous').disabled=receiptPage===0;$('next').disabled=receiptPage>=receipts.length-1;}
for(const button of document.querySelectorAll('[data-view]'))button.addEventListener('click',()=>{for(const pane of document.querySelectorAll('[data-pane]'))pane.hidden=pane.dataset.pane!==button.dataset.view;});
$('previous').addEventListener('click',()=>{receiptPage--;evidence();});$('next').addEventListener('click',()=>{receiptPage++;evidence();});
async function call(s,path,body){const r=await fetch(`${s.api}/${path}`,{method:body?'POST':'GET',headers:{'content-type':'application/json',...(s.bootstrap?{'x-pulse-session':s.bootstrap}:s.session?{authorization:'Bearer '+s.session}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
async function refresh(){const s=await state();$('pause').textContent=s.paused?'Resume tracking':'Pause tracking';const current=$('notice').value;$('notice').replaceChildren(...(s.policy?.notices??[]).map(n=>{const o=document.createElement('option');o.value=n.id;o.textContent=n.version;return o;}));$('notice').value=current||s.policy?.notices?.[0]?.id||'';receipts=ownedEvents(s.seen,s);evidence();const {last}=await chrome.storage.session.get('last');$('context').textContent=last?`${last.domain} · project matched · recent foreground sample`:'No current mapped work domain. Suspended timer gaps stay unknown.';$('status').textContent=s.issue??(s.session?`${s.paused?'Paused':'Tracking mapped work resources'} · ${(s.outbox??[]).length} waiting to sync`:'Sign in with Pulse credentials.');}
function action(fn){return async e=>{e?.preventDefault();try{await fn();await refresh();}catch(error){$('status').textContent=String(error);}};}
$('login').addEventListener('submit',action(async()=>{let s=await state();if(s.session)throw Error('Sign out before changing identity or API address.');const api=$('api').value.replace(/\/$/,'');if(!api.startsWith('https://'))throw Error('Use HTTPS');const u=new URL(api);await chrome.permissions.request({origins:[`${u.origin}/*`]});const d=await call({api},'auth/sign-in',{username:$('username').value,password:$('password').value});$('password').value='';if(d.mustChange)throw Error('Change your issued password in Pulse first.');s={api,bootstrap:d.token};const me=await call(s,'me');const policy=await call(s,'devices/policy');const profile=await chrome.identity.getProfileUserInfo({accountStatus:'ANY'});if(!profile.email||profile.email.toLowerCase()!==me.email?.toLowerCase())throw Error('Use the Chrome work profile matching your Pulse company email.');const device=await call(s,'devices',{name:'Pulse Chrome work profile',platform:'chrome'});const issued=await call(s,'native/exchange',{deviceId:device.id});await save({api,session:issued.accessToken,deviceId:device.id,personId:me.person,policy,paused:true,trackingEpoch:crypto.randomUUID(),outbox:[],seen:[]});}));
$('allow').addEventListener('click',action(async()=>{const s=await state();if(!s.session)throw Error('Connect first');const policy=await call(s,'devices/policy');if(!policy.domains.length)throw Error('Your admin has not configured work domains.');await chrome.permissions.request({origins:policy.domains.map(d=>`https://${d}/*`)});await save({policy});}));
$('pause').addEventListener('click',action(async()=>{const s=await state();if(!s.session)throw Error('Connect first');await chrome.storage.session.remove('last');if(!s.paused){await save({paused:true,trackingEpoch:crypto.randomUUID(),outbox:[]});await call(s,`devices/${s.deviceId}/pause`,{paused:true});return;}
 const policy=await call(s,'devices/policy');const notice=policy.notices.find(n=>n.id===$('notice').value);if(!notice)throw Error('Select an approved purpose notice');const endsAt=new Date($('endsAt').value).toISOString();await call(s,`devices/${s.deviceId}/consent`,{purposes:['work_sites'],notice:notice.id});const capture=await call(s,`devices/${s.deviceId}/resume`,{endsAt});await save({paused:false,receipt:capture.receipts.find(r=>r.purpose==='work_sites').id,shiftEnd:Date.parse(capture.endsAt),workWindow:notice.body.workWindow,policy:{...policy,domains:policy.domains.filter(d=>notice.body.domains.includes(d))},sourceSession:crypto.randomUUID(),sequence:0,trackingEpoch:crypto.randomUUID(),outbox:[]});
}));
$('sync').addEventListener('click',action(async()=>{await chrome.runtime.sendMessage({type:'sync'});}));
$('logout').addEventListener('click',action(async()=>{const s=await state();await chrome.storage.local.clear();await chrome.storage.session.clear();await save({paused:true,trackingEpoch:crypto.randomUUID()});if(s.session){try{await call(s,`devices/${s.deviceId}/revoke`,{});}catch{ $('status').textContent='Signed out locally. Revoke this device in Pulse Settings when online.';}}}));
void refresh();

let developerTaps=0;document.querySelector('h1').addEventListener('click',()=>{if(++developerTaps===7)document.getElementById('developerServer').hidden=false;});
