import {nativeTokens} from '../../packages/design-system/src/native';
import React,{useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Alert,AppState,Linking,Platform,Pressable,ScrollView,StyleSheet,Switch,Text,TextInput,useColorScheme,View} from 'react-native';
import {SafeAreaProvider,SafeAreaView} from 'react-native-safe-area-context';
import * as Haptics from 'expo-haptics';
import * as Location from 'expo-location';
import NetInfo from '@react-native-community/netinfo';
import * as Notifications from 'expo-notifications';
import {applyLocal,celebration,clockOffset,demoPayload,type ActionId,type CompanionPayload,type CompanionState,type Mode,type Prefs,type PresenceDecision} from '../../packages/companion/src/index.js';
import {cached,currentPerson,currentIdentity,pause,resume,subscribeChats,consent,device,enroll,flush,init,load,queueShoot,request,signIn,finishSignIn,signOut,uuid,within,pairStart,pairPoll,pairCancel,type Identity} from './src/client';
import {act as companionAct,checkHere,flushQueue,loadDay,readPrefs,responseAction,scheduleReminders,setupNotifications,startPresence,stopPresence,writePrefs,type PresenceStatus} from './src/companion';
import {CompanionSettings,Suggestion,TodayCard} from './src/today';
import {Pip} from './src/pip';
import {refreshWidget} from './src/widget';
import {refreshNativeSurfaces,handleRibbonEvent} from './src/native-surfaces';
import notifee from '@notifee/react-native';
const tabs=['Today','My desk','Tasks','Chats','People','Projects'] as const;
type Tab=typeof tabs[number];
const paths:Record<Tab,string>={'Today':'intelligence?surface=dashboard','My desk':'hr/self','Tasks':'delivery','Chats':'chats','People':'people','Projects':'projects?scope=all'};
const DEFAULT_API='https://pulse.estateautopilots.com/api/native/v0';
function Button({label,onPress,primary=true}:{label:string;onPress:()=>void;primary?:boolean}){return <Pressable accessibilityRole="button" onPress={onPress} style={[styles.button,!primary&&styles.buttonQuiet]}><Text style={[styles.buttonText,!primary&&styles.buttonQuietText]}>{label}</Text></Pressable>;}
export default function App(){return <SafeAreaProvider><Pulse/></SafeAreaProvider>;}
function Pulse(){
 const dark=useColorScheme()==='dark';const theme=nativeTokens[dark?'dark':'light'];const fg=theme.text;const bg=theme.canvas;
 const [ready,setReady]=useState(false),[me,setMe]=useState<Identity|null>(null),[tab,setTab]=useState<Tab>('Today'),[data,setData]=useState<any>(null),[stamp,setStamp]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [api,setApi]=useState(DEFAULT_API),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[next,setNext]=useState(''),[challenge,setChallenge]=useState(''),[otp,setOtp]=useState('');
 const [developer,setDeveloper]=useState(false);
 const [signInMode,setSignInMode]=useState<'start'|'code'|'password'>('start'),[pairCode,setPairCode]=useState(''),[pairUrl,setPairUrl]=useState('');
 const [channel,setChannel]=useState<any>(null),[messages,setMessages]=useState<any[]>([]),[draft,setDraft]=useState(''),[sendId,setSendId]=useState(uuid());
 const [geo,setGeo]=useState(false),[policy,setPolicy]=useState<any>({shoots:[]}),[permission,setPermission]=useState(false);
 const [from,setFrom]=useState(new Date().toLocaleDateString('en-CA')),[to,setTo]=useState(from),[leaveKind,setLeaveKind]=useState(''),[reason,setReason]=useState('');
 // Companion: the day, the person's choices, office suggestions, the demo.
 const [day,setDay]=useState<{payload:CompanionPayload;offset:number}|null>(null),[prefs,setPrefs]=useState<Prefs|null>(null),[mode,setMode]=useState<Mode>('office');
 const [status,setStatus]=useState<{text:string;tone?:'success'|'warning'}|null>(null),[celebrate,setCelebrate]=useState(false),[presence,setPresence]=useState<PresenceStatus|null>(null);
 const [suggestion,setSuggestion]=useState<{decision:PresenceDecision;body:Record<string,unknown>}|null>(null),[demo,setDemo]=useState<CompanionPayload|null>(null);
 const [widgetLink,setWidgetLink]=useState<{action:ActionId;entry:string;state:string}|null>(null);
 const handled=useRef(new Set<string>());
 async function act(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);if([401,403].includes((e as {status?:number}).status??0))setData(null);}finally{setBusy(false);}}
 async function refresh(){if(tab==='Today'&&!data){const old=await cached(paths.Today);if(old)setData(old.data);}const old=await cached(paths[tab]);if(old){setData(old.data);setStamp(`As of ${new Date(old.at).toLocaleTimeString()}`);}const r=await load(paths[tab]);setData(r.data);setStamp(`${r.offline?'Offline · ':''}As of ${new Date(r.at).toLocaleTimeString()}`);}
 const refreshDay=useCallback(async(opts:{schedule?:boolean;here?:boolean}={})=>{
  const sent=await flushQueue().catch(()=>null);
  if(sent?.expired)setStatus({text:`${sent.expired} saved tap${sent.expired>1?'s were':' was'} older than 3 hours. Ask for a correction on My desk.`,tone:'warning'});
  const d=await loadDay();if(!d)return;const offset=clockOffset(d.payload);setDay({payload:d.payload,offset});
  if(d.offline)setStatus(s=>s??{text:`Offline · showing ${new Date(d.at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}${d.queued?` · ${d.queued} saved on this phone`:''}`});
  const p=await readPrefs();setPrefs(p);refreshWidget(d.payload);void refreshNativeSurfaces(d.payload,p).catch(()=>{});
  if(opts.schedule)await scheduleReminders(d.payload,p).catch(()=>{});
  if(opts.here&&!d.offline){const here=await checkHere(d.payload).catch(()=>null);if(here&&here.decision.kind==='suggest-check-in')setSuggestion({decision:here.decision,body:{via:'mobile',trigger:'suggested',mode:here.decision.mode,place:{kind:here.signal.place.kind,id:here.signal.place.placeId,signal:here.signal.trigger==='wifi'?'wifi':'gps'}}});}
 },[]);
 async function connected(){const m=await enroll(Platform.OS);if(currentPerson()!==m.person)return;setMe(m);if(!m.mustChange){setPolicy(await request('devices/policy'));const d=await request('devices');const purposes=d.devices.find((x:any)=>x.id===device())?.purposes??[];setPermission(purposes.includes('shoot_presence'));await request(`devices/${device()}/health`,{health:'healthy',appVersion:'0.2.0',capabilities:{foreground_location:'unknown',background_location:'unknown',push:'unknown'}});await setupNotifications().catch(()=>{});const p=await readPrefs();setPrefs(p);await refreshDay({schedule:true,here:true});if(p.presence){const d=await loadDay().catch(()=>null);if(d)setPresence(await startPresence(d.payload).catch(()=>null));}}}
 // One tap on the card, a suggestion, a widget-like notification button: same rules as My desk.
 async function companion(id:ActionId,extra:Record<string,unknown>={}){
  if(demo){const p={...applyLocal(demo,id,Date.now(),{mode,...extra}),pending:false};setDemo(p);void refreshNativeSurfaces(p,prefs??undefined).catch(()=>{});refreshWidget(p);setStatus({text:'Demo · nothing is saved',tone:'success'});if(id==='check-in'){setCelebrate(true);setTimeout(()=>setCelebrate(false),4000);}void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(()=>{});return;}
  setBusy(true);setStatus(null);
  try{const body=id==='check-in'?{mode,...extra}:extra;const r=await companionAct(id,body);void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(()=>{});
   await refreshDay({schedule:true});
   setStatus(r.queued?{text:'Saved on this phone · Pulse will catch up when you’re online',tone:'success'}:{text:id==='check-in'?'Checked in. Have a good day!':id==='break-start'?'Enjoy your break':id==='break-end'?'Welcome back':'Checked out. See you tomorrow!',tone:'success'});
   if(id==='check-in'&&!r.queued){const d=await loadDay().catch(()=>null);const party=d&&d.payload.entry&&!d.payload.entry.late?celebration(d.payload):null;if(party){setStatus(null);setCelebrate(true);setTimeout(()=>setCelebrate(false),4200);}}
  }catch(e){setStatus({text:(e as Error).message,tone:'warning'});void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error).catch(()=>{});}
  finally{setBusy(false);}
 }
 async function changePrefs(change:Partial<Prefs>){
  const p=await writePrefs(change);setPrefs(p);
  if('presence' in change&&day){if(change.presence){const st=await startPresence(day.payload).catch(e=>({on:false,background:false,regions:0,note:(e as Error).message}));setPresence(st);if(!st.on)setPrefs(await writePrefs({presence:false}));}else{await stopPresence().catch(()=>{});setPresence(null);}}
  if(['checkIn','checkOut','breakBack','breakMinutes'].some(k=>k in change))await scheduleReminders(day?.payload??null,p).catch(()=>{});
 }
 function startDemo(state:CompanionState='out'){const p=demoPayload(state,Date.now(),state==='in'?{waiting:2}:{});setDemo(p);refreshWidget(p);void refreshNativeSurfaces(p).catch(()=>{});setTab('Today');setStatus({text:'Demo · nothing is saved'});}
 useEffect(()=>{void act(async()=>{try{if(await init()){try{await connected();}catch(e){if((e as {offline?:boolean}).offline){setMe(currentIdentity());await refreshDay().catch(()=>{});}else throw e;}}}finally{setReady(true);}});},[]);
 // pulse://demo?state=in (screenshots and "Try it" links) shows the synthetic day.
 useEffect(()=>{const open=(url:string|null)=>{if(!url)return;const m=url.match(/^pulse:\/\/demo(?:\?state=([a-z]+))?/);if(m)startDemo((m[1]??'out') as CompanionState);if(url.startsWith('pulse://attendance?')){const q=new URL(url).searchParams;const action=q.get('action') as ActionId;if(['check-in','break-start','break-end','check-out'].includes(action)){setTab('Today');setWidgetLink({action,entry:q.get('entry')??'',state:q.get('state')??''});}}if(url==='pulse://today')setTab('Today');};void Linking.getInitialURL().then(open);const sub=Linking.addEventListener('url',e=>open(e.url));return()=>sub.remove();},[]);
 useEffect(()=>{if(me&&!me.mustChange)void act(refresh);},[me,tab]);
 // Notification buttons (Check in / I'm back / Check out / Take a break) from reminders and office suggestions.
 useEffect(()=>{if(!me||me.mustChange)return;const run=(response:Notifications.NotificationResponse|null)=>{if(!response)return;const key=response.notification.request.identifier+':'+response.actionIdentifier;if(handled.current.has(key))return;handled.current.add(key);const a=responseAction(response);if(a){setTab('Today');void companion(a.action,a.extra);}};void Notifications.getLastNotificationResponseAsync().then(run);const sub=Notifications.addNotificationResponseReceivedListener(run);return()=>sub.remove();},[me,mode]);
 useEffect(()=>{if(!me||me.mustChange)return;const sub=Notifications.addNotificationResponseReceivedListener(response=>{const notificationId=response.notification.request.content.data?.notificationId;if(typeof notificationId!=='string'||!/^[0-9a-f-]{36}$/.test(notificationId))return;setChannel(null);setMessages([]);void act(async()=>{const opened=await request(`native/notifications/${notificationId}/open`);const messages=await request(`chats/${opened.record.id}/messages`);setTab('Chats');setChannel(opened.record);setMessages(messages.messages);});});return()=>sub.remove();},[me]);
 useEffect(()=>{if(!me||me.mustChange)return;const sync=()=>{void flush();if(tab==='Chats')void refresh().catch(()=>{});if(channel)void request(`chats/${channel.id}/messages`).then(d=>setMessages(d.messages)).catch(()=>{});};const controller=new AbortController();void subscribeChats(sync,controller.signal);const timer=setInterval(sync,15000);const sub=AppState.addEventListener('change',s=>{if(s==='active'){sync();void refreshDay({here:true}).catch(()=>{});}});return()=>{clearInterval(timer);controller.abort();sub.remove();};},[me,tab,channel]);
 // Foreground Wi-Fi changes provide indoor arrival suggestions without reading GPS or polling.
 useEffect(()=>{if(!me||me.mustChange||!prefs?.presence)return;return NetInfo.addEventListener(net=>{if(AppState.currentState==='active')void refreshDay({here:true}).catch(()=>{});});},[me,prefs?.presence]);
 useEffect(()=>{if(!me||me.mustChange)return;const stop=notifee.onForegroundEvent(event=>{void handleRibbonEvent(event).then(()=>refreshDay()).catch(()=>{});});const timer=setInterval(()=>{if(AppState.currentState==='active')void refreshDay({here:true}).catch(()=>{});},30000);return()=>{stop();clearInterval(timer);};},[me]);
 useEffect(()=>{if(!widgetLink||!me||me.mustChange)return;const link=widgetLink;setWidgetLink(null);void loadDay().then(d=>{if(!d||d.payload.state!==link.state||(d.payload.entry?.id??'')!==link.entry){setStatus({text:'Your day changed. Choose an action on Today.',tone:'warning'});return;}Alert.alert('Pulse',link.action==='check-in'?'Check in now?':link.action==='check-out'?'Check out now?':link.action==='break-start'?'Start your break?':'Back from your break?',[{text:'Cancel'},{text:'Confirm',onPress:()=>void companion(link.action,{trigger:'widget'})}]);}).catch(()=>{});},[widgetLink,me]);
 // Browser sign-in: wait for the approval while the app is open.
 useEffect(()=>{if(signInMode!=='code')return;const timer=setInterval(()=>{void pairPoll().then(async s=>{if(s==='approved'){clearInterval(timer);setSignInMode('start');await act(connected);}else if(s!=='pending'){clearInterval(timer);setSignInMode('start');setError(s==='denied'?'Not approved. Nothing was signed in.':'The code expired. Start again when you’re ready.');}}).catch(e=>{if(!(e as {offline?:boolean}).offline){clearInterval(timer);setSignInMode('start');setError((e as Error).message);}});},3000);return()=>clearInterval(timer);},[signInMode]);
 const text=(s:string)=> <Text style={{color:fg,fontSize:16,lineHeight:24}}>{s}</Text>;
 const muted=(s:string)=> <Text style={{color:theme.muted,fontSize:14,lineHeight:20}}>{s}</Text>;
 const field=(value:string,set:(s:string)=>void,placeholder:string,secure=false)=><TextInput accessibilityLabel={placeholder} placeholder={placeholder} placeholderTextColor={theme.muted} value={value} onChangeText={set} secureTextEntry={secure} autoCapitalize="none" style={[styles.input,{color:fg,borderColor:theme.border}]}/>;
 const card=(key:string,children:React.ReactNode)=><View key={key} style={[styles.card,{backgroundColor:theme.surface}]}>{children}</View>;
 async function shoot(s:any,transition='presence'){const person=me?.person;if(!person||currentPerson()!==person)throw Error('Sign in first');if(!permission)throw Error('Enable shoot declarations first');let inside:boolean|null=null;let dwellSeconds=0;let method='declared';if(geo){const p=await Location.requestForegroundPermissionsAsync();if(p.granted){const first=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});if(within(first.coords.latitude,first.coords.longitude,s,first.coords.accuracy)){const began=Date.now();await new Promise(resolve=>setTimeout(resolve,30000));if(AppState.currentState!=='active'||currentPerson()!==person)throw Error('Location dwell interrupted · presence unknown. Manual check-in remains available.');const second=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});inside=within(second.coords.latitude,second.coords.longitude,s,second.coords.accuracy);dwellSeconds=Math.floor((Date.now()-began)/1000);if(inside)method='foreground';}}if(method==='declared')Alert.alert('Location unknown','Denied, inaccurate or wrong-site signals cannot confirm presence. Your manual declaration remains available.');}const confirmed=await new Promise<boolean>(resolve=>Alert.alert('Confirm shoot declaration',inside?'Approximate site match after dwell. Only site ID, time, accuracy class and your purpose receipt are sent.':'Manual declaration · location unknown. This does not automatically change attendance.',[{text:'Cancel',onPress:()=>resolve(false)},{text:'Confirm',onPress:()=>resolve(true)}],{cancelable:false}));if(!confirmed)return;const out=await queueShoot(s.projectId,{shootId:s.id,inside,method,transition,confirmed:true,...(method==='foreground'?{accuracyClass:'site_precision',dwellSeconds}:{})},person);Alert.alert('Shoot evidence',out.pending?'Pending verification · encrypted on this phone until acknowledged.':'Personal evidence received · no automatic delivery credit.');}
 async function pushes(){if(Platform.OS==='android')await Notifications.setNotificationChannelAsync('work-updates',{name:'Work updates',importance:Notifications.AndroidImportance.DEFAULT});const p=await Notifications.requestPermissionsAsync();if(!p.granted)throw Error('Notifications were declined');const d=await Notifications.getDevicePushTokenAsync();await request(`devices/${device()}/push`,{token:d.data});Alert.alert('Notifications enabled','Pulse will send generic work alerts when your admin configures APNs or FCM.');}
 const open=(href:string)=>void Linking.openURL(new URL(href,api).href);
 if(!ready)return <SafeAreaView style={{flex:1,backgroundColor:bg,alignItems:'center',justifyContent:'center',gap:12}}><Pip mood="waking" size={96} dark={dark}/><ActivityIndicator/>{error?text(error):null}</SafeAreaView>;
 const shownDay=demo??day?.payload??null;
 const today=(demo||(me&&!me.mustChange))?<>
  {suggestion&&!demo?<Suggestion decision={suggestion.decision} theme={theme} onAct={id=>{const b=suggestion.body;setSuggestion(null);void companion(id,id==='check-in'?b:{via:'mobile',trigger:'suggested'});}} onDismiss={()=>setSuggestion(null)}/>:null}
  <TodayCard payload={shownDay} offset={demo?0:day?.offset??0} theme={theme} dark={dark} busy={busy} status={status} mode={mode} onMode={setMode} onAct={id=>void companion(id)} onOpen={open} celebrate={celebrate} showPip={prefs?.mascot??true}/>
  {prefs&&!demo?<CompanionSettings prefs={prefs} payload={shownDay} presence={presence} theme={theme} onPrefs={p=>void changePrefs(p)}/>:null}
  {demo?card('demo',<>{text('This is a demo day with made-up times.')}{muted('Sign in with your Pulse account to check in for real.')}<Button label="Leave the demo" onPress={()=>{setDemo(null);setStatus(null);}}/></>):null}
 </>:null;
 return <SafeAreaView style={{flex:1,backgroundColor:bg}}><View style={styles.header}><Text onLongPress={()=>setDeveloper(true)} style={[styles.brand,{color:fg}]}>pulse<Text style={{color:theme.action}}> ·</Text></Text>{me&&!me.mustChange?<Button primary={false} label="Sign out" onPress={()=>Alert.alert('Sign out of Pulse?','This phone stops checking you in and forgets its saved data.',[{text:'Cancel'},{text:'Sign out',style:'destructive',onPress:()=>void act(async()=>{setMe(null);setData(null);setDay(null);setMessages([]);setChannel(null);setDraft('');setReason('');setPassword('');setPermission(false);setGeo(false);setPolicy({shoots:[]});await stopPresence().catch(()=>{});await Notifications.cancelAllScheduledNotificationsAsync().catch(()=>{});await signOut();refreshWidget(null);await refreshNativeSurfaces(null);})}])}/>:null}</View>
 <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
 {error?<Text accessibilityRole="alert" style={{color:dark?'#ffb2a8':'#9c332a',fontSize:15}}>{error}</Text>:null}{busy&&tab!=='Today'?<ActivityIndicator/>:null}
 {demo&&!me?today:!me?card('login',<>
  <View style={{alignItems:'center',gap:6}}><Pip mood={signInMode==='code'?'waking':'idle'} size={112} dark={dark}/><Text style={[styles.title,{color:fg,textAlign:'center'}]}>{signInMode==='code'?'Approve in your browser':'Hi, I’m Pip'}</Text>{muted(signInMode==='code'?'Your browser opened Pulse. Check it shows this code, then press Approve.':'Check in, take a break and check out with one tap — the same rules as My desk.')}</View>
  {signInMode==='code'?<><Text selectable accessibilityLabel={`Code ${pairCode.split('').join(' ')}`} style={[styles.code,{color:fg,backgroundColor:theme.selected}]}>{pairCode}</Text><ActivityIndicator/><Button primary={false} label="Open the page again" onPress={()=>void Linking.openURL(pairUrl)}/><Button primary={false} label="Cancel" onPress={()=>{pairCancel();setSignInMode('start');}}/></>
  :signInMode==='password'?<>{developer?field(api,setApi,'Developer server'):null}{field(username,setUsername,'Pulse username')}{field(password,setPassword,'Password',true)}{challenge?field(otp,setOtp,'Authenticator or recovery code'):null}<Button label={challenge?'Verify':'Sign in'} onPress={()=>void act(async()=>{const r=challenge?await finishSignIn(challenge,otp):await signIn(api,username,password);if(r.twoStep){setChallenge(r.challenge);return;}setChallenge('');setOtp('');await connected();setPassword('');})}/><Button primary={false} label="Forgot password or username" onPress={()=>void Linking.openURL(new URL('/login',api).href)}/><Button primary={false} label="Back" onPress={()=>setSignInMode('start')}/></>
  :<>{developer?field(api,setApi,'Developer server'):null}<Button label="Sign in with your Pulse account" onPress={()=>void act(async()=>{const p=await pairStart(api,Platform.OS,Platform.OS==='ios'?'Pulse on iPhone':'Pulse on Android');setPairCode(p.code);setPairUrl(p.url);setSignInMode('code');await Linking.openURL(p.url);})}/><Button primary={false} label="Use username and password" onPress={()=>setSignInMode('password')}/><Pressable accessibilityRole="button" onPress={()=>startDemo('out')}><Text style={{color:theme.action,fontWeight:'600',textAlign:'center',padding:8}}>Try it without signing in</Text></Pressable></>}
 </>):me.mustChange?card('change',<>{text('Choose your own password before opening Pulse.')}{field(password,setPassword,'Issued password',true)}{field(next,setNext,'New password · at least 10 characters',true)}<Button label="Save password" onPress={()=>void act(async()=>{await request('auth/change-password',{current:password,next});setPassword('');setNext('');await connected();})}/></>):<>
 {tab!=='Today'?<><Text style={[styles.title,{color:fg}]}>{tab}</Text>{muted(stamp)}</>:null}
 {tab==='Today'?<>{today}{data?card('home',<>{text('Your work today')}{(data.cards??[]).slice(0,4).map((c:any)=><View key={c.id}>{text(c.headline)}{muted(c.meaning)}</View>)}{!data.cards?.length?muted('No work cards yet.'):null}<Button primary={false} label="Enable work notifications" onPress={()=>void act(pushes)}/><Button primary={false} label="What Pulse saw today" onPress={()=>void act(async()=>{const e=await request('events/today');Alert.alert('Your activity',e.events.map((x:any)=>`${x.kind} · ${new Date(x.at).toLocaleTimeString()}`).join('\n')||'No activity received today.');})}/></>):null}</>:null}
 {tab==='My desk'&&data?<>{card('desk',<>{text(`Today · ${data.now?.state??'unknown'}`)}{muted('Check in, breaks and check-out live on Today. Corrections and leave are here.')}<Button label="Open Today" onPress={()=>setTab('Today')}/></>)}
 {card('shoots',<>{text('On-site shoots')}<View style={styles.row}>{text('Allow shoot declarations')}<Switch accessibilityLabel="Allow shoot declarations" value={permission} onValueChange={x=>void act(async()=>{await consent(x?['shoot_presence']:[]);setPermission(x);})}/></View><View style={styles.row}>{text('Optional location · 30-second dwell')}<Switch accessibilityLabel="Optional shoot geofence" value={geo} onValueChange={setGeo}/></View>{muted('Location is requested only when you tap a shoot. Pulse stores the result, never coordinates.')}<Button primary={false} label="Confirm shift end · next 8 hours" onPress={()=>void act(async()=>{await resume(new Date(Date.now()+8*3600000).toISOString());})}/><Button primary={false} label="Pause sensing now" onPress={()=>void act(pause)}/>{policy.shoots.map((s:any)=><View key={s.id}>{text(s.label)}{muted('Call sheet: '+s.startsAt+' → '+s.endsAt)}{muted('Check: approved site, brief and accepted-footage handoff in project tasks.')}<Button label="Started" onPress={()=>void act(()=>shoot(s,'started'))}/><Button primary={false} label="Wrapped" onPress={()=>void act(()=>shoot(s,'wrapped'))}/></View>)}{!policy.shoots.length?muted('No shoots configured by your admin.'):null}</>)}
 {card('leave',<>{text('Request leave')}{field(from,setFrom,'From · YYYY-MM-DD')}{field(to,setTo,'To · YYYY-MM-DD')}<View style={styles.row}>{(data.leave?.types??[]).map((t:any)=><Button key={t.key} primary={leaveKind===t.key} label={`${leaveKind===t.key?'✓ ':''}${t.name}`} onPress={()=>setLeaveKind(t.key)}/>)}</View>{field(reason,setReason,'Reason')}<Button label="Send leave request" onPress={()=>void act(async()=>{await request('leave',{fromDate:from,toDate:to,kind:leaveKind,reason});setReason('');await refresh();})}/><Button primary={false} label="Send HR request" onPress={()=>void act(async()=>{await request('hr/tickets',{category:'other',subject:reason.slice(0,120),body:reason});setReason('');await refresh();})}/></>)}
 </>:null}
 {tab==='Chats'?channel?<>{card('channel',<>{text(channel.name)}<Button primary={false} label="All conversations" onPress={()=>{setChannel(null);setMessages([]);}}/>{messages.map(m=><View key={m.id} style={[styles.message,{borderColor:theme.border}]}>{text(m.name)}{text(m.removed?'Message removed':m.body)}</View>)}{field(draft,s=>{setDraft(s);setSendId(uuid());},'Message')}<Button label="Send message" onPress={()=>void act(async()=>{await request(`chats/${channel.id}/messages`,{body:draft,clientId:sendId});setDraft('');setSendId(uuid());setMessages((await request(`chats/${channel.id}/messages`)).messages);})}/></>)}</>:(data?.channels??[]).map((c:any)=>card(c.id,<Button primary={false} label={`${c.name} · ${c.unread} unread`} onPress={()=>void act(async()=>{setChannel(c);setMessages((await request(`chats/${c.id}/messages`)).messages);await request(`chats/${c.id}/read`,{});})}/>)):null}
 {tab==='Tasks'?(data?.tasks??[]).map((t:any)=>card(t.id,<>{text(t.title)}{muted(`${t.state??t.status} · ${data.project?.title??t.projectName??'No project'}`)}{(t.checklist??[]).map((i:any)=><Text key={i.label} style={{color:fg}}>{i.done?'✓':'○'} {i.label}</Text>)}</>)):null}
 {tab==='People'?(data?.people??[]).map((p:any)=>card(p.id,<>{text(p.name)}{muted(`${p.role??'Team member'} · ${p.pod??''}`)}</>)):null}
 {tab==='Projects'?(data?.projects??[]).map((p:any)=>card(p.projectId,<>{text(p.title)}{muted(p.clientName??'')}</>)):null}
 </>}
 </ScrollView>{me&&!me.mustChange?<ScrollView horizontal showsHorizontalScrollIndicator={false} style={[styles.nav,{borderColor:theme.border}]} contentContainerStyle={styles.row}>{tabs.map(t=><Pressable key={t} accessibilityRole="tab" accessibilityState={{selected:tab===t}} onPress={()=>{setTab(t);setData(null);setChannel(null);}} style={[styles.tab,tab===t&&{backgroundColor:theme.selected}]}><Text style={{color:fg,fontWeight:tab===t?'700':'400'}}>{t}</Text></Pressable>)}</ScrollView>:null}</SafeAreaView>;
}
const styles=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:20,paddingVertical:8},brand:{fontSize:30,fontWeight:'700'},title:{fontSize:26,fontWeight:'700'},content:{padding:16,gap:14,paddingBottom:28},card:{padding:18,borderRadius:22,gap:12},input:{minHeight:50,borderWidth:1,borderRadius:12,padding:12,fontSize:16},button:{backgroundColor:'#5b45d6',paddingHorizontal:16,paddingVertical:14,borderRadius:14,minHeight:50,alignItems:'center',justifyContent:'center'},buttonQuiet:{backgroundColor:'transparent',borderWidth:1,borderColor:'#c5c7d8'},buttonText:{color:'#fff',fontWeight:'700',fontSize:15},buttonQuietText:{color:'#5b45d6'},row:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:8},message:{paddingVertical:12,borderBottomWidth:StyleSheet.hairlineWidth},nav:{flexGrow:0,maxHeight:62,padding:8,borderTopWidth:StyleSheet.hairlineWidth},tab:{padding:14,borderRadius:12,minHeight:44},code:{fontSize:32,fontWeight:'800',letterSpacing:4,textAlign:'center',paddingVertical:14,borderRadius:14,overflow:'hidden'}});
