const $=id=>document.getElementById(id);const invoke=(cmd,args)=>window.__TAURI__.core.invoke(cmd,args);let state;let authChallenge='';let pending=false;let uiEpoch=0;let evidencePage=0;
function paintEvidence(){const items=state?.seen??[];evidencePage=Math.min(evidencePage,Math.max(0,items.length-1));$('seen').replaceChildren();const pre=document.createElement('pre');pre.textContent=items.length?JSON.stringify(items[evidencePage],null,2):'No permitted evidence received. Missing source signals stay unknown.';$('seen').append(pre);$('evidencePage').textContent=items.length?`${evidencePage+1} / ${items.length}`:'No receipts';$('previousEvidence').disabled=evidencePage===0;$('nextEvidence').disabled=evidencePage>=items.length-1;}
for(const b of document.querySelectorAll('[data-view]'))b.addEventListener('click',()=>{for(const pane of document.querySelectorAll('[data-pane]'))pane.hidden=pane.dataset.pane!==b.dataset.view;paintEvidence();});
for(const b of document.querySelectorAll('[data-step]'))b.addEventListener('click',()=>{for(const pane of document.querySelectorAll('[data-form-step]'))pane.hidden=pane.dataset.formStep!==b.dataset.step;});
$('previousEvidence').addEventListener('click',()=>{evidencePage--;paintEvidence();});$('nextEvidence').addEventListener('click',()=>{evidencePage++;paintEvidence();});
const showError=e=>{$('status').textContent=String(e);};
async function refresh(){if(pending)return;pending=true;const expected=uiEpoch;try{const next=await invoke('tracker_status');if(expected!==uiEpoch)return;state=next;$('status').textContent=[state.configured?`Tracking for ${state.personName}${state.connected?'':' · offline'}`:'Sign in to enable tracking',state.paused?'Paused':state.configured?`Active until ${new Date(state.captureEnd).toLocaleTimeString()}`:'No collection',`${state.queued} events waiting to upload`,state.issue,state.breakWarning].filter(Boolean).join(' · ');$('pause').textContent=state.paused?'Resume tracking':'Pause tracking';paintEvidence();}catch(e){showError(e);}finally{pending=false;}}
$('connect').addEventListener('submit',async e=>{e.preventDefault();if(pending)return;pending=true;const expected=++uiEpoch;try{const api=$('api').value;if(!$('username').value||!$('password').value)throw Error('Enter your Pulse credentials in Account first');const login=authChallenge?await invoke('tracker_verify_login',{api,challenge:authChallenge,code:$('authCode').value}):await invoke('tracker_login',{api,username:$('username').value,password:$('password').value});if(login.twoStep){authChallenge=login.challenge;$('twoStepField').hidden=false;throw Error('Enter an authenticator or recovery code, then sign in again.');}authChallenge='';$('twoStepField').hidden=true;$('authCode').value='';$('password').value='';if(expected!==uiEpoch)return;if(login.mustChange)throw Error('Change your issued password in the Pulse workspace before enrolling this computer.');await invoke('tracker_configure',{settings:{api,projectId:$('projectId').value.trim()||null,session:login.token,refreshToken:'',receipts:{},captureEnd:'',allowTools:[],personId:'',personName:'',deviceId:state?.deviceId??'',purposes:[$('usage').checked?'activity_context':null,$('evidence').checked?'work_evidence':null,$('commands').checked?'command_counts':null,$('declarations').checked?'declarations':null].filter(Boolean),folders:$('folders').value.split('\n').map(s=>s.trim()).filter(Boolean),workStart:Number($('start').value),workEnd:Number($('end').value),breakTools:[...$('breakTools').selectedOptions].map(o=>o.value)}});}catch(e){showError(e);}finally{pending=false;}await refresh();});
$('pause').addEventListener('click',async()=>{try{await invoke('tracker_pause',{paused:!state.paused});await refresh();}catch(e){showError(e);}});
$('workspace').addEventListener('click',()=>invoke('open_workspace').catch(showError));
$('signout').addEventListener('click',async()=>{++uiEpoch;state=null;$('username').value='';$('password').value='';$('seen').replaceChildren();$('bridgeInfo').textContent='';$('bridgeInfo').hidden=true;for(const id of ['usage','evidence','commands','declarations'])$(id).checked=false;$('folders').value='';$('status').textContent='Signing out · no new collection';try{await invoke('tracker_sign_out');await refresh();}catch(e){showError(e);}});
await refresh();if(state){$('usage').checked=state.purposes.includes('activity_context');$('evidence').checked=state.purposes.includes('work_evidence');$('commands').checked=state.purposes.includes('command_counts');$('declarations').checked=state.purposes.includes('declarations');$('folders').value=state.folders.join('\n');}setInterval(refresh,5000);

$('bridge').addEventListener('click',async()=>{try{$('bridgeInfo').hidden=false;$('bridgeInfo').textContent=JSON.stringify(await invoke('bridge_info'),null,2);}catch(e){showError(e);}});

$('accountRecovery').addEventListener('click',e=>{e.preventDefault();invoke('tracker_open_recovery').catch(showError);});

let developerTaps=0;document.querySelector('h1').addEventListener('click',()=>{if(++developerTaps===7)document.getElementById('developerServer').hidden=false;});
