const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const ts=require('typescript');
function fixture(){
 const secure=new Map(),cache=new Map(),outbox=new Map(),attendance=new Map(),requests=[],keychainOptions=new Map();let person='person-one',heldFetch,heldCache,heldSecure,heldAttendance,offline=false;
 const db={execAsync:async sql=>{if(sql.includes('DELETE FROM cache'))cache.clear();if(sql.includes('DELETE FROM outbox'))outbox.clear();if(sql.includes('DELETE FROM attendance_queue'))attendance.clear();},getFirstAsync:async(sql,key)=>{if(sql==='PRAGMA cipher_version')return {cipher_version:'synthetic-test-cipher'};const row=cache.get(key);if(heldCache)return new Promise(resolve=>{heldCache={resolve,row};});return row??null;},getAllAsync:async sql=>[...(sql.includes('attendance_queue')?attendance:outbox).values()],runAsync:async(sql,...args)=>{if(sql.startsWith('INSERT OR REPLACE INTO cache'))cache.set(args[0],{data:args[1],at:args[2]});if(sql.startsWith('INSERT INTO outbox'))outbox.set(args[0],{id:args[0],data:args[1]});if(sql.startsWith('INSERT INTO attendance_queue')){if(heldAttendance===true)await new Promise(resolve=>{heldAttendance={resolve};});attendance.set(args[0],{id:args[0],data:args[1]});}if(sql.startsWith('DELETE FROM outbox'))outbox.delete(args[0]);}};
 const exports={};const module={exports};
 const stubs={'expo-crypto':{randomUUID:()=>crypto.randomUUID()},'expo-secure-store':{AFTER_FIRST_UNLOCK:17,getItemAsync:async key=>secure.get(key)??null,setItemAsync:async(key,value,options)=>{keychainOptions.set(key,options);if(heldSecure===key)await new Promise(resolve=>{heldSecure={resolve};});secure.set(key,value);},deleteItemAsync:async key=>secure.delete(key)},'expo-sqlite':{openDatabaseAsync:async(_name,options)=>{if(!options?.useNewConnection)return db;let keyed=false;return {execAsync:async sql=>{if(sql.startsWith('PRAGMA key=')){keyed=sql.includes(secure.get('pulse.cache-key'));return;}if(!keyed)throw Error('unkeyed SQLCipher connection');await db.execAsync(sql);},runAsync:async(...args)=>{if(!keyed)throw Error('unkeyed SQLCipher connection');await db.runAsync(...args);},withTransactionAsync:async task=>{if(!keyed)throw Error('unkeyed SQLCipher connection');await task();},closeAsync:async()=>{}};}},'expo-constants':{expoConfig:{extra:{apiUrl:'https://native.example.test/api/native/v0'}}}};
 const fetch=async(url,options)=>{requests.push({url,headers:options.headers,body:options.body?JSON.parse(options.body):null});if(offline)throw Error('offline');const path=url.split('/v0/')[1];let data=path==='native/exchange'?{accessToken:'access-'+person,refreshToken:'refresh-'+person}:path==='devices/policy'?{notices:[{id:'notice',body:{dataItems:['explicit_shoot_wrap']}}]}:path.endsWith('/resume')?{endsAt:new Date(Date.now()+3600000).toISOString(),receipts:[{id:'receipt',purpose:'shoot_presence'}]}:path==='native/batches'?{acknowledged:[JSON.parse(options.body).events[0].id]}:path==='auth/sign-in'?{token:'token-'+person}:path==='me'?{person,name:person,role:'person',mustChange:false}:path==='devices'?{devices:[{id:'device-'+person,revokedAt:null}]}:path==='hr/self'?{privateNote:person}:{};if(path==='devices'&&options.method==='POST')data={id:'device-'+person};if(path==='hr/self'&&heldFetch)return new Promise(resolve=>{heldFetch={resolve,data};});return {ok:true,json:async()=>data};};
 const code=ts.transpileModule(fs.readFileSync(__dirname+'/../src/client.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
 vm.runInNewContext(code,{exports,module,require:name=>stubs[name],fetch,crypto,AbortSignal,TextDecoder,Date,URL,setTimeout,clearTimeout});
 return {client:module.exports,keychainOptions,secure,cache,outbox,requests,person:value=>person=value,holdFetch:()=>{heldFetch=true;},resolveFetch:()=>{const h=heldFetch;heldFetch=null;h.resolve({ok:true,json:async()=>h.data});},holdCache:()=>{heldCache=true;},resolveCache:()=>{const h=heldCache;heldCache=null;h.resolve(h.row);},holdSecure:key=>heldSecure=key,secureHeld:()=>typeof heldSecure==='object',resolveSecure:()=>{const held=heldSecure;heldSecure=null;held.resolve();},offline:value=>offline=value,holdAttendance:()=>{heldAttendance=true;},attendanceHeld:()=>typeof heldAttendance==='object',resolveAttendance:()=>{const held=heldAttendance;heldAttendance=null;held.resolve();}};
}
async function login(f,person='person-one'){f.person(person);await f.client.signIn('https://native.example.test/api/native/v0','tester','synthetic');await f.client.enroll('android');}
test('late private response cannot repopulate cache after switching identity',async()=>{
 const f=fixture();await f.client.init();await login(f);f.holdFetch();const pending=f.client.load('hr/self');await Promise.resolve();await f.client.signOut();await login(f,'person-two');f.resolveFetch();await assert.rejects(pending,/sign-in changed/);assert.equal(f.cache.size,0);const fresh=await f.client.load('hr/self');assert.equal(fresh.data.privateNote,'person-two');assert.equal((await f.client.cached('hr/self')).data.privateNote,'person-two');
});
test('a cache read resolving after logout returns no previous-person data',async()=>{
 const f=fixture();await f.client.init();await login(f);await f.client.load('hr/self');f.holdCache();const pending=f.client.cached('hr/self');await Promise.resolve();await f.client.signOut();await login(f,'person-two');f.resolveCache();assert.equal(await pending,null);
});
test('offline logout clears local identity, credential and cache before revocation succeeds',async()=>{
 const f=fixture();await f.client.init();await login(f);await f.client.load('hr/self');f.secure.set('pulse.companion-prefs',JSON.stringify({presence:true,autoCheckIn:true}));f.secure.set('pulse.presence-recent','[]');f.offline(true);await f.client.signOut();assert.equal(f.client.currentPerson(),null);assert.equal(f.secure.has('pulse.session'),false);assert.equal(f.cache.size,0);assert.equal(f.secure.has('pulse.companion-prefs'),false,'the next person must consent themselves');assert.equal(f.secure.has('pulse.presence-recent'),false);
});

test('an attendance queue write captured before switching account is refused',async()=>{
 const f=fixture();await f.client.init();await login(f);const old=f.client.sessionGeneration();await f.client.signOut();await login(f,'person-two');await assert.rejects(f.client.queueWrite([{id:'former-person-tap'}],old),/sign-in changed/);
});

test('attendance queue uses a keyed connection and survives restart, then clears on logout',async()=>{
 const f=fixture();await f.client.init();await login(f);const tap={id:'attendance-tap',action:'check-in',at:new Date().toISOString()};await f.client.queueWrite([tap]);await f.client.init();assert.deepEqual(JSON.parse(JSON.stringify(await f.client.queueRead())),[tap]);await f.client.signOut();assert.deepEqual(JSON.parse(JSON.stringify(await f.client.queueRead())),[]);
});

test('logout waits for an in-flight attendance write and removes it before another person signs in',async()=>{
 const f=fixture();await f.client.init();await login(f);f.holdAttendance();const pending=f.client.queueWrite([{id:'old-person-tap'}]).then(()=>null,error=>error);for(let i=0;i<50&&!f.attendanceHeld();i++)await new Promise(resolve=>setImmediate(resolve));assert.equal(f.attendanceHeld(),true);const logout=f.client.signOut();f.resolveAttendance();assert.match(String(await pending),/sign-in changed/);await logout;await login(f,'person-two');assert.deepEqual(JSON.parse(JSON.stringify(await f.client.queueRead())),[]);
});
test('shoot result from the former person cannot be queued for a new identity',async()=>{
 const f=fixture();await f.client.init();await login(f);await f.client.signOut();await login(f,'person-two');await assert.rejects(f.client.queueShoot('project',{inside:true},'person-one'),/sign-in changed/);assert.equal(f.outbox.size,0);
});
test('geofence requires reported accuracy and the uncertainty circle inside the shoot',()=>{
 const f=fixture(),shoot={latitude:19,longitude:73,radiusMeters:100,precision:'verified_site',startsAt:new Date(Date.now()-3600000).toISOString(),endsAt:new Date(Date.now()+3600000).toISOString()};assert.equal(f.client.within(19,73,shoot,20),true);assert.equal(f.client.within(19,73,shoot,null),false);assert.equal(f.client.within(19,73,shoot,6000),false);assert.equal(f.client.within(19.1,73,shoot,20),false);
});

test('encrypted queue survives source restart and deletes only acknowledged IDs',async()=>{const f=fixture();await f.client.init();await login(f);await f.client.consent(['shoot_presence']);await f.client.resume(new Date(Date.now()+3600000).toISOString());f.offline(true);const result=await f.client.queueShoot('synthetic-project',{shootId:'synthetic-shoot',inside:null,method:'declared'},'person-one');assert.equal(result.pending,1);assert.equal(f.outbox.size,1);await f.client.init();assert.equal(f.client.currentPerson(),'person-one');f.offline(false);await f.client.flush();assert.equal(f.outbox.size,0);const upload=f.requests.find(r=>r.url.endsWith('native/batches'));assert.ok(upload.body.events[0].consentReceipt);assert.ok(upload.body.events[0].sourceSession);assert.equal(upload.body.events[0].sequence,0);});
test('offline pause removes disallowed queue before network failure',async()=>{const f=fixture();await f.client.init();await login(f);await f.client.consent(['shoot_presence']);await f.client.resume(new Date(Date.now()+3600000).toISOString());f.offline(true);await f.client.queueShoot('project',{shootId:'shoot',inside:null,method:'declared'},'person-one');await assert.rejects(f.client.pause(),/Offline/);assert.equal(f.outbox.size,0);await assert.rejects(f.client.queueShoot('project',{},'person-one'),/purpose receipt/);});
test('site precision, nearby wrong site and expired shoot stay unknown',()=>{const f=fixture();const site={latitude:19,longitude:73,radiusMeters:100,precision:'verified_site',startsAt:new Date(Date.now()-10000).toISOString(),endsAt:new Date(Date.now()+10000).toISOString()};for(const patch of [{precision:'city'},{radiusMeters:5000},{endsAt:'2000-01-01T00:00:00Z'}])assert.equal(f.client.within(19,73,{...site,...patch},10),false);assert.equal(f.client.within(19.01,73,site,10),false);assert.equal(f.client.within(19,73,site,100),false);});

test('an OS credential write finishing during logout cannot restore a session',async()=>{const f=fixture();await f.client.init();f.holdSecure('pulse.session');const pending=login(f).then(()=>null,error=>error);for(let i=0;i<50&&!f.secureHeld();i++)await new Promise(resolve=>setImmediate(resolve));assert.equal(f.secureHeld(),true);const logout=f.client.signOut();f.resolveSecure();assert.match(String(await pending),/sign-in changed/);await logout;assert.equal(f.secure.has('pulse.session'),false);assert.equal(f.secure.has('pulse.refresh'),false);assert.equal(f.client.currentPerson(),null);});

test('background credentials and migrated consent remain available after the first device unlock',async()=>{
 const f=fixture();f.secure.set('pulse.companion-prefs','{"presence":true}');f.secure.set('pulse.presence-recent','[]');await f.client.init();await login(f);
 for(const key of ['pulse.cache-key','pulse.api','pulse.session','pulse.refresh','pulse.device','pulse.person','pulse.identity','pulse.companion-prefs','pulse.presence-recent'])assert.equal(f.keychainOptions.get(key)?.keychainAccessible,17,key);
 await f.client.init();assert.equal(f.keychainOptions.get('pulse.cache-key')?.keychainAccessible,17);
});
