const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');
const policy=require(path.resolve(__dirname,'../../../packages/companion/src/updates.js'));
function fixture(os='android'){
 let status=200;let calls=[];const url='https://github.com/Estate-Autopilots/pulse-companion/releases/download/companion-v0.3.2-abc123/Pulse-0.3.2-android.apk';
 const manifest={version:'0.3.2',channel:'test',notes:'Updates',platforms:{},files:[{name:'Pulse-0.3.2-android.apk',platform:'android',kind:'apk',url,size:42,sha256:'a'.repeat(64)}]};
 const stubs={'react-native':{Platform:{OS:os},NativeModules:{PulseInstaller:{download:async(...args)=>{calls.push(args);return 'verified.apk';},canInstall:async()=>false,openPermission:async()=>{},install:async()=> 'permission'}}},'expo-constants':{__esModule:true,default:{expoConfig:{version:'0.3.1'}}},'../../../packages/companion/src/updates.js':policy};
 const source=ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../src/updates.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const module={exports:{}};
 vm.runInNewContext(source,{module,exports:module.exports,require:n=>{if(!(n in stubs))throw Error(n);return stubs[n];},fetch:async()=>({status,ok:status===200,json:async()=>manifest})});
 return {api:module.exports,manifest,calls,status:v=>status=v};
}
test('Android checks only its selected channel and hands verified release metadata to native downloader',async()=>{const f=fixture();const update=await f.api.checkUpdates();assert.equal(update.version,'0.3.2');assert.equal(await f.api.prepareUpdate(update),'verified.apk');assert.deepEqual(f.calls[0],[f.manifest.files[0].url,'a'.repeat(64),42]);await assert.rejects(f.api.checkUpdates('stable'));await assert.rejects(f.api.checkUpdates('unknown'));});
test('no update for same/older version, 204, offline, or iPhone',async()=>{const f=fixture();f.manifest.version='0.3.1';assert.equal(await f.api.checkUpdates(),null);f.manifest.version='0.2.9';assert.equal(await f.api.checkUpdates(),null);f.status(204);assert.equal(await f.api.checkUpdates(),null);f.status(503);await assert.rejects(f.api.checkUpdates());assert.equal(await fixture('ios').api.checkUpdates(),null);});
test('APK handoff asks Android for first-time permission and does not pretend installation succeeded',async()=>{const f=fixture();assert.equal(await f.api.canInstallUpdate(),false);assert.equal(await f.api.installUpdate('verified.apk'),'permission');f.manifest.files[0].url='https://evil.test/update.apk';await assert.rejects(f.api.checkUpdates());});
